# pqc_pqcrypto_compat.py — generated by PQC Scanner
# Stable wrapper over pqcrypto's ML-DSA / ML-KEM modules.
#
# pqcrypto 1.0 renamed generate_keypair->keygen, encrypt->encaps and
# decrypt->decaps, and changed verify() from returning a bool to returning None
# and raising on a bad signature. This module keeps one stable surface so the
# migrated call sites do not have to care.
#
# Requires: pqcrypto>=1.0.0,<2
from pqcrypto.kem import ml_kem_512 as _ml_kem_512
from pqcrypto.kem import ml_kem_768 as _ml_kem_768
from pqcrypto.kem import ml_kem_1024 as _ml_kem_1024
from pqcrypto.sign import ml_dsa_44 as _ml_dsa_44
from pqcrypto.sign import ml_dsa_65 as _ml_dsa_65
from pqcrypto.sign import ml_dsa_87 as _ml_dsa_87


class _Sign:
    """ML-DSA signature surface."""

    def __init__(self, module):
        self._m = module

    def generate_keypair(self):
        """Return (public_key, secret_key)."""
        return self._m.keygen()

    def sign(self, secret_key, message):
        """Return the signature bytes for `message`."""
        return self._m.sign(secret_key, message)

    def verify(self, public_key, message, signature):
        """Return True if the signature is valid, False if it is not.

        pqcrypto raises on a bad signature and returns None on a good one, so
        forwarding the return value would invert the answer for every caller
        written as `if verify(...)`.
        """
        try:
            self._m.verify(public_key, message, signature)
        except Exception:
            return False
        return True


class _Kem:
    """ML-KEM key-encapsulation surface."""

    def __init__(self, module):
        self._m = module

    def generate_keypair(self):
        """Return (public_key, secret_key)."""
        return self._m.keygen()

    def encrypt(self, public_key):
        """Encapsulate. Return (ciphertext, shared_secret)."""
        return self._m.encaps(public_key)

    def decrypt(self, secret_key, ciphertext):
        """Decapsulate. Return the shared secret."""
        return self._m.decaps(secret_key, ciphertext)


# Two alias spellings, because the two emitters differ: the LibCST pattern
# handlers write `mldsa44`, the recipe planner writes `ml_dsa_65`. Both name the
# same object, so a file that somehow imported both still behaves identically.
mldsa44 = ml_dsa_44 = _Sign(_ml_dsa_44)
mldsa65 = ml_dsa_65 = _Sign(_ml_dsa_65)
mldsa87 = ml_dsa_87 = _Sign(_ml_dsa_87)
mlkem512 = ml_kem_512 = _Kem(_ml_kem_512)
mlkem768 = ml_kem_768 = _Kem(_ml_kem_768)
mlkem1024 = ml_kem_1024 = _Kem(_ml_kem_1024)
